variables:
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"

build_job:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: build
  script:
    - ARTIFACT_PATH="${PWD}/artifacts/"
    - mkdir -pv $ARTIFACT_PATH
    - dotnet build -c Release
    - dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - cp RipVanBluRay.Service/bin/Release/net5.0/linux-x64/publish/rvbr $ARTIFACT_PATH
    - ls -lsah $ARTIFACT_PATH
  artifacts:
    name: "RipVanBluRay Executable"
    paths:
      - "artifacts/rvbr"
    expire_in: 1 week
