name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: linux

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Add Nuget Source
      run: dotnet nuget remove source gitea || dotnet nuget add source --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text --name gitea ${{ secrets.NUGET_URL }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Publish
    #   run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: rvbr
    #     path: RipVanBluRay.Service/bin/Release/net8.0/linux-x64/publish/


